variable "eks_cluster" {
  type = object({
    cluster_id : string,
    cluster_arn : string,
    cluster_endpoint : string,
    cluster_ca : string,
    cluster_oidc_issuer_url : string,
    cluster_version : string,
    worker_iam_role_name : string,
    worker_security_group : string,
    oidc_provider_arn : string,
  })
  description = "EKS cluster information"
}

variable "tags" {
  description = "Standard tags. Typically generated by fogg"
  type = object({
    env : string,
    owner : string,
    project : string,
    service : string,
    managedBy : string,
  })
}

variable "image_name" {
  type    = string
  default = "626314663667.dkr.ecr.us-west-2.amazonaws.com/aws-ssm"
}

variable "image_tag" {
  type    = string
  default = "arm64"
}

variable "namespace" {
  description = "Kubernetes namespace for all resources"
  type        = string
}

variable "iam_role_path" {
  type        = string
  description = "IAM Path for the IAM role created for the service. If omitted, defaults to /{eks_cluster_id}-{service}/"
  default     = ""
}
