# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "aws-iam-password-policy" {
  source = "github.com/chanzuckerberg/cztack//aws-iam-password-policy?ref=v0.104.2"



}
