# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "configuration_endpoint_address" {
  value     = module.elasticache_secure.configuration_endpoint_address
  sensitive = false
}

output "port" {
  value     = module.elasticache_secure.port
  sensitive = false
}

output "primary_endpoint_address" {
  value     = module.elasticache_secure.primary_endpoint_address
  sensitive = false
}


