# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

include scripts/common.mk

ENVS=dev prod sandbox staging
MODULES=alb-http-v0.484.6 aws-elasticsearch-v0.199.1 aws-elb-access-logs-bucket-v0.420.0 aws-env-v4.0.0 aws-iam-policy-s3-reader-v0.420.0 aws-iam-policy-s3-writer-v0.66.0 config czid-services-private-key ecs-cluster-v2.4.0 ecs-service-with-alb-v0.421.0 happy-env-eks happy-github-ci-role happy-github-ci-role-ecs happy-github-ci-role-eks idseq-s3-tar-writer individual-attr instance-cloud-init-script-v0.484.6 k8s-core-v5.5.1 kubernetes-aws-ssm-k8s-core-v5 kubernetes-secret-from-aws-param-v0.395.0 machine-images panther-s3-ingest-v2.0.1 snowflake-stage-s3-role-v0.420.0 waf-georestriction-main web-acl-regional-v3.3.1
ACCOUNTS=idseq-dev idseq-prod idseq-staging idseq-support

all: check

setup: ## set up working directory by installing dependencies
	curl -s https://raw.githubusercontent.com/chanzuckerberg/fogg/v0.92.46/download.sh | bash -s -- -b .fogg/bin v0.92.46
	.fogg/bin/fogg setup
.PHONY: setup

lint: lint-terraform ## lint the code in this repo
.PHONY: lint

lint-terraform: lint-accounts lint-envs lint-modules ## lint the terraform code in this repo
.PHONY: lint-terraform

lint-accounts:  ## lint the terrarform code in terraform/accounts
	@for account in $(ACCOUNTS); do \
		$(MAKE) -C terraform/accounts/$$account lint || exit $$?; \
	done
.PHONY: lint-accounts

lint-envs: ## lint the terraform code in terraform/envs
	@for env in $(ENVS); do \
		$(MAKE) -C terraform/envs/$$env lint || exit $$?; \
	done; \
	$(MAKE) -C terraform/global lint || exit $$?
.PHONY: lint-envs

lint-modules: ## lint the terraform code in terraform/modules
	@for module in $(MODULES); do \
		$(MAKE) -C terraform/modules/$$module lint || exit $$?; \
	done
.PHONY: lint-modules

fmt: fmt-fogg fmt-accounts fmt-envs fmt-global fmt-modules ## format code in this repo
.PHONY: fmt

fmt-fogg:
	.fogg/bin/fogg fmt
.PHONY: fmt-fogg

fmt-accounts: ## format code in terraform/accounts
	@for account in $(ACCOUNTS); do \
		$(MAKE) -C terraform/accounts/$$account fmt || exit $$?; \
	done
.PHONY: fmt-accounts

fmt-envs: ## format the code in teraform/envs
	@for env in $(ENVS); do \
		$(MAKE) -C terraform/envs/$$env fmt || exit $$?; \
	done
.PHONY: fmt-envs

fmt-global: ## format the code in terraform/global
	$(MAKE) -C terraform/global fmt || exit $$?
.PHONY: fmt-global

fmt-modules:  ## format the code in terraform/modules
	@for module in $(MODULES); do \
		$(MAKE) -C terraform/modules/$$module fmt || exit $$?; \
	done
.PHONY: fmt-modules

docs: docs-envs docs-global docs-modules ## update docs
.PHONY: docs

docs-accounts: ## update docs in terraform/accounts
	@for account in $(ACCOUNTS); do \
		$(MAKE) -C terraform/accounts/$$account docs || exit $$?; \
	done
.PHONY: docs-accounts

docs-envs: ## update the docs in terraform/envs
	@for env in $(ENVS); do \
		$(MAKE) -C terraform/envs/$$env docs || exit $$?; \
	done
.PHONY: docs-envs

docs-global: ## update the docs in terraform/global
	$(MAKE) -C terraform/global docs || exit $$?;
.PHONY: docs-global

docs-modules: ## update the docs in terraform/modules
	@for module in $(MODULES); do \
		$(MAKE) -C terraform/modules/$$module docs || exit $$?; \
	done
.PHONY: docs-modules

test:
.PHONY: test

check: check-plan check-docs ## check all code in the repo
.PHONY: check

check-plan: check-plan-accounts check-plan-envs check-plan-global ## check terraform plans across all components
.PHONY: check-plan

check-plan-accounts: ## check terraform plans in terraform/accounts
	@for account in $(ACCOUNTS); do \
		$(MAKE) -C terraform/accounts/$$account check-plan || exit $$?; \
	done
.PHONY: check-plan-accounts

check-plan-envs: ## check terraform plans in terraform/envs
	@for env in $(ENVS); do \
		$(MAKE) -C terraform/envs/$$env check-plan || exit $$?; \
	done
.PHONY: check-plan-envs

check-plan-global: ## check terraform plans in terraform/global
	$(MAKE) -C terraform/global check-plan || exit $$?
.PHONY: check-plan-global

check-docs: ## check terraform docs
	@for mod in $(MODULES); do \
		$(MAKE) -C terraform/modules/$$module check-docs || exit $$?; \
	done
.PHONY: check-docs

clean: clean-accounts clean-envs clean-global ## clean the repo
.PHONY: clean

clean-accounts: ## clean in terraform/accounts
	@for account in $(ACCOUNTS); do \
		$(MAKE) -C terraform/accounts/$$account clean || exit $$?; \
	done
.PHONY: clean-accounts

clean-envs: ## clean in terraform/envs
	@for env in $(ENVS); do \
		$(MAKE) -C terraform/envs/$$env clean || exit $$?; \
	done
.PHONY: clean-envs

clean-global: ## clean in terraform/global
	$(MAKE) -C terraform/global clean || exit $$?
.PHONY: clean-global


help: ## display help for this makefile
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
.PHONY: help

