# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "comp_bio_role_arn" {
  value     = module.individual-attr.comp_bio_role_arn
  sensitive = false
}

output "on_call_role_arn" {
  value     = module.individual-attr.on_call_role_arn
  sensitive = false
}


