# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "github-actions-runner-permissions" {
  source                      = "../../../modules/github-actions-runner-permissions"
  account_id                  = local.account_id
  env                         = local.env
  s3_bucket_idseq_bench       = local.s3_bucket_idseq_bench
  s3_bucket_public_references = local.s3_bucket_public_references
  s3_bucket_samples           = local.s3_bucket_samples
  s3_bucket_workflows         = local.s3_bucket_workflows
  tags                        = local.tags



}
