# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "gh_actions_executor_role" {
  value     = module.github-actions-runner-permissions.gh_actions_executor_role
  sensitive = false
}


