# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "czid-services-private-key" {
  source = "../../../modules/czid-services-private-key"
  env    = local.env



}
