# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "private_key_pem" {
  value     = module.czid-services-private-key.private_key_pem
  sensitive = true
}

output "public_key_openssh" {
  value     = module.czid-services-private-key.public_key_openssh
  sensitive = false
}

output "public_key_pem" {
  value     = module.czid-services-private-key.public_key_pem
  sensitive = false
}


