# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "eks-cluster" {
  source                  = "github.com/chanzuckerberg/cztack//aws-eks-cluster?ref=v0.104.2"
  addons                  = local.addons
  authorized_github_repos = local.authorized_github_repos
  cluster_name            = local.cluster_name
  cluster_version         = local.cluster_version
  node_groups             = local.node_groups
  owner_roles             = local.owner_roles
  subnet_ids              = local.subnet_ids
  tags                    = local.tags
  vpc_id                  = local.vpc_id


  providers = {
    aws.us-east-1 = aws.us-east-1
  }
}
