# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "happy" {
  source               = "../../../modules/happy-env-eks"
  additional_secrets   = local.additional_secrets
  base_zone_id         = local.base_zone_id
  cloud-env            = local.cloud-env
  ecr_repos            = local.ecr_repos
  eks-cluster          = local.eks-cluster
  github_actions_roles = local.github_actions_roles
  s3_buckets           = local.s3_buckets
  tags                 = local.tags


  providers = {
    aws.czi-si = aws.czi-si
  }
}
