# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "cluster_arn" {
  value     = module.eks-cluster.cluster_arn
  sensitive = false
}

output "cluster_ca" {
  value     = module.eks-cluster.cluster_ca
  sensitive = false
}

output "cluster_certificate_authority_data" {
  value     = module.eks-cluster.cluster_certificate_authority_data
  sensitive = false
}

output "cluster_endpoint" {
  value     = module.eks-cluster.cluster_endpoint
  sensitive = false
}

output "cluster_iam_role_name" {
  value     = module.eks-cluster.cluster_iam_role_name
  sensitive = false
}

output "cluster_id" {
  value     = module.eks-cluster.cluster_id
  sensitive = false
}

output "cluster_oidc_issuer_url" {
  value     = module.eks-cluster.cluster_oidc_issuer_url
  sensitive = false
}

output "cluster_primary_security_group_id" {
  value     = module.eks-cluster.cluster_primary_security_group_id
  sensitive = false
}

output "cluster_security_group" {
  value     = module.eks-cluster.cluster_security_group
  sensitive = false
}

output "cluster_version" {
  value     = module.eks-cluster.cluster_version
  sensitive = false
}

output "gh_action_role" {
  value     = module.eks-cluster.gh_action_role
  sensitive = false
}

output "oidc_provider_arn" {
  value     = module.eks-cluster.oidc_provider_arn
  sensitive = false
}

output "s3_csi_role_arn" {
  value     = module.eks-cluster.s3_csi_role_arn
  sensitive = false
}

output "s3_csi_role_name" {
  value     = module.eks-cluster.s3_csi_role_name
  sensitive = false
}

output "secrets_key_arn" {
  value     = module.eks-cluster.secrets_key_arn
  sensitive = false
}

output "worker_iam_role_name" {
  value     = module.eks-cluster.worker_iam_role_name
  sensitive = false
}

output "worker_security_group" {
  value     = module.eks-cluster.worker_security_group
  sensitive = false
}


