# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

SHELL=/bin/bash -o pipefail
TF_VARS := $(patsubst %,-e%,$(filter TF_VAR_%,$(.VARIABLES)))
REPO_ROOT := $(shell git rev-parse --show-toplevel)
REPO_RELATIVE_PATH := $(shell git rev-parse --show-prefix)
AUTO_APPROVE := false
export AWS_SDK_LOAD_CONFIG := 1

# CZ ID stack runs on OpenTofu, not Terraform (Constitution Principle II).
# OpenTofu reads the same TF_* env vars and *.tf as Terraform, so the engine
# command is the only change here. fogg emits the Terraform/tfenv tooling; a
# future `fogg apply` must re-apply this swap (see specs/002-tofu-conversion).
export PATH := $(REPO_ROOT)/.fogg/bin:$(PATH)
export TF_PLUGIN_CACHE_DIR=$(REPO_ROOT)/.terraform.d/plugin-cache
export TF_IN_AUTOMATION=1
tofu_command ?= tofu

ifeq ($(TF_BACKEND_KIND),remote)
	REFRESH := true
else
	REFRESH := false
endif


tofu: ## ensure OpenTofu (tofu) is installed and on PATH
	@command -v $(tofu_command) >/dev/null 2>&1 || { \
		echo "OpenTofu not found on PATH. Install it: 'brew install opentofu',"; \
		echo "or via tenv (https://github.com/tofuutils/tenv), or the"; \
		echo "opentofu/setup-opentofu action in CI. Pinned version:"; \
		cat $(REPO_ROOT)/.opentofu-version 2>/dev/null; \
		exit 1; \
	}
.PHONY: tofu
