# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.
variable "TFC_WORKSPACE_NAME" {
  type    = string
  default = "unknown"
}
variable "TFC_WORKSPACE_SLUG" {
  type    = string
  default = "unknown"
}
variable "TFC_CONFIGURATION_VERSION_GIT_BRANCH" {
  type    = string
  default = "unknown"
}
variable "TFC_CONFIGURATION_VERSION_GIT_TAG" {
  type    = string
  default = "unknown"
}
variable "TFC_PROJECT_NAME" {
  type    = string
  default = "unknown"
}
provider "aws" {

  region  = "us-west-2"
  profile = "idseq-staging"

  # this is the new way of injecting AWS tags to all AWS resources
  # var.tags should be considered deprecated
  default_tags {
    tags = {
      TFC_WORKSPACE_NAME                   = coalesce(var.TFC_WORKSPACE_NAME, "unknown")
      TFC_WORKSPACE_SLUG                   = coalesce(var.TFC_WORKSPACE_SLUG, "unknown")
      TFC_CONFIGURATION_VERSION_GIT_BRANCH = coalesce(var.TFC_CONFIGURATION_VERSION_GIT_BRANCH, "unknown")
      TFC_CONFIGURATION_VERSION_GIT_TAG    = coalesce(var.TFC_CONFIGURATION_VERSION_GIT_TAG, "unknown")
      TFC_PROJECT_NAME                     = coalesce(var.TFC_PROJECT_NAME, "unknown")
      project                              = coalesce(var.tags.project, "unknown")
      env                                  = coalesce(var.tags.env, "unknown")
      service                              = coalesce(var.tags.service, "unknown")
      owner                                = coalesce(var.tags.owner, "unknown")
      managedBy                            = "terraform"
    }
  }
  allowed_account_ids = ["030998640247"]
}
# Aliased Providers (for doing things in every region).


provider "aws" {
  alias   = "czi-si-us-east-1"
  region  = "us-east-1"
  profile = "idseq-prod"

  # this is the new way of injecting AWS tags to all AWS resources
  # var.tags should be considered deprecated
  default_tags {
    tags = {
      TFC_WORKSPACE_NAME                   = coalesce(var.TFC_WORKSPACE_NAME, "unknown")
      TFC_WORKSPACE_SLUG                   = coalesce(var.TFC_WORKSPACE_SLUG, "unknown")
      TFC_CONFIGURATION_VERSION_GIT_BRANCH = coalesce(var.TFC_CONFIGURATION_VERSION_GIT_BRANCH, "unknown")
      TFC_CONFIGURATION_VERSION_GIT_TAG    = coalesce(var.TFC_CONFIGURATION_VERSION_GIT_TAG, "unknown")
      TFC_PROJECT_NAME                     = coalesce(var.TFC_PROJECT_NAME, "unknown")
      project                              = coalesce(var.tags.project, "unknown")
      env                                  = coalesce(var.tags.env, "unknown")
      service                              = coalesce(var.tags.service, "unknown")
      owner                                = coalesce(var.tags.owner, "unknown")
      managedBy                            = "terraform"
    }
  }
  allowed_account_ids = ["283694049553"]
}


provider "aws" {
  alias   = "czi-si"
  region  = "us-west-2"
  profile = "idseq-prod"

  # this is the new way of injecting AWS tags to all AWS resources
  # var.tags should be considered deprecated
  default_tags {
    tags = {
      TFC_WORKSPACE_NAME                   = coalesce(var.TFC_WORKSPACE_NAME, "unknown")
      TFC_WORKSPACE_SLUG                   = coalesce(var.TFC_WORKSPACE_SLUG, "unknown")
      TFC_CONFIGURATION_VERSION_GIT_BRANCH = coalesce(var.TFC_CONFIGURATION_VERSION_GIT_BRANCH, "unknown")
      TFC_CONFIGURATION_VERSION_GIT_TAG    = coalesce(var.TFC_CONFIGURATION_VERSION_GIT_TAG, "unknown")
      TFC_PROJECT_NAME                     = coalesce(var.TFC_PROJECT_NAME, "unknown")
      project                              = coalesce(var.tags.project, "unknown")
      env                                  = coalesce(var.tags.env, "unknown")
      service                              = coalesce(var.tags.service, "unknown")
      owner                                = coalesce(var.tags.owner, "unknown")
      managedBy                            = "terraform"
    }
  }
  allowed_account_ids = ["283694049553"]
}


provider "aws" {
  alias   = "us-east-1"
  region  = "us-east-1"
  profile = "idseq-staging"

  # this is the new way of injecting AWS tags to all AWS resources
  # var.tags should be considered deprecated
  default_tags {
    tags = {
      TFC_WORKSPACE_NAME                   = coalesce(var.TFC_WORKSPACE_NAME, "unknown")
      TFC_WORKSPACE_SLUG                   = coalesce(var.TFC_WORKSPACE_SLUG, "unknown")
      TFC_CONFIGURATION_VERSION_GIT_BRANCH = coalesce(var.TFC_CONFIGURATION_VERSION_GIT_BRANCH, "unknown")
      TFC_CONFIGURATION_VERSION_GIT_TAG    = coalesce(var.TFC_CONFIGURATION_VERSION_GIT_TAG, "unknown")
      TFC_PROJECT_NAME                     = coalesce(var.TFC_PROJECT_NAME, "unknown")
      project                              = coalesce(var.tags.project, "unknown")
      env                                  = coalesce(var.tags.env, "unknown")
      service                              = coalesce(var.tags.service, "unknown")
      owner                                = coalesce(var.tags.owner, "unknown")
      managedBy                            = "terraform"
    }
  }
  allowed_account_ids = ["030998640247"]
}


provider "assert" {}
terraform {
  required_version = "=1.14.8"

  backend "s3" {

    bucket = "tfstate-030998640247"

    key     = "terraform/idseq/envs/staging/components/heatmap-optimization.tfstate"
    encrypt = true
    region  = "us-west-2"
    profile = "idseq-staging"


  }
  required_providers {

    archive = {
      source = "hashicorp/archive"

      version = "~> 2.0"

    }

    assert = {
      source = "bwoznicki/assert"

      version = "0.0.1"

    }

    aws = {
      source = "hashicorp/aws"

      version = "~> 5.100.0"

    }

    helm = {
      source = "hashicorp/helm"

      version = "~> 2.17.0"

    }

    kubectl = {
      source = "gavinbunney/kubectl"

      version = "~> 1.19.0"

    }

    kubernetes = {
      source = "hashicorp/kubernetes"

      version = "~> 3.1.0"

    }

    local = {
      source = "hashicorp/local"

      version = "~> 2.0"

    }

    null = {
      source = "hashicorp/null"

      version = "3.1.1"

    }

    okta-head = {
      source = "okta/okta"

      version = "> 3.30"

    }

    random = {
      source = "hashicorp/random"

      version = "~> 3.4"

    }

    tls = {
      source = "hashicorp/tls"

      version = "~> 3.0"

    }

  }
}
# tflint-ignore: terraform_unused_declarations
variable "env" {
  type    = string
  default = "staging"
}
# tflint-ignore: terraform_unused_declarations
variable "project" {
  type    = string
  default = "idseq"
}
# tflint-ignore: terraform_unused_declarations
variable "region" {
  type    = string
  default = "us-west-2"
}
# tflint-ignore: terraform_unused_declarations
variable "component" {
  type    = string
  default = "heatmap-optimization"
}
# tflint-ignore: terraform_unused_declarations
variable "aws_profile" {
  type    = string
  default = "idseq-staging"
}
# tflint-ignore: terraform_unused_declarations
variable "owner" {
  type    = string
  default = "biohub-tech@chanzuckerberg.com"
}
# tflint-ignore: terraform_unused_declarations
# DEPRECATED: this field is deprecated in favor or 
# AWS provider default tags.
variable "tags" {
  type = object({ project : string, env : string, service : string, owner : string, managedBy : string })
  default = {
    project   = "idseq"
    env       = "staging"
    service   = "heatmap-optimization"
    owner     = "biohub-tech@chanzuckerberg.com"
    managedBy = "terraform"
  }
}
# tflint-ignore: terraform_unused_declarations
variable "alignment_index_date" {
  type    = string
  default = "2021-01-22"
}
# tflint-ignore: terraform_unused_declarations
variable "base_domain" {
  type    = string
  default = "seqtoid.org"
}
# tflint-ignore: terraform_unused_declarations
variable "build_index_date" {
  type    = string
  default = "2021-01-22"
}
# tflint-ignore: terraform_unused_declarations
variable "eks_cluster_name" {
  type    = string
  default = "czid-staging-eks"
}
# tflint-ignore: terraform_unused_declarations
variable "s3_bucket_aegea_ecs_execute" {
  type    = string
  default = "aegea-ecs-execute-staging-030998640247"
}
# tflint-ignore: terraform_unused_declarations
variable "s3_bucket_idseq_bench" {
  type    = string
  default = "idseq-bench"
}
# tflint-ignore: terraform_unused_declarations
variable "s3_bucket_public_references" {
  type    = string
  default = "seqtoid-public-references"
}
# tflint-ignore: terraform_unused_declarations
variable "s3_bucket_samples" {
  type    = string
  default = "idseq-samples-staging-030998640247"
}
# tflint-ignore: terraform_unused_declarations
variable "s3_bucket_samples_v1" {
  type    = string
  default = "czi-infectious-disease-staging-samples-030998640247"
}
# tflint-ignore: terraform_unused_declarations
variable "s3_bucket_secrets" {
  type    = string
  default = "idseq-secrets"
}
data "terraform_remote_state" "cloud-env" {
  backend = "s3"
  config = {


    bucket = "tfstate-030998640247"

    key     = "terraform/idseq/envs/staging/components/cloud-env.tfstate"
    region  = "us-west-2"
    profile = "idseq-staging"


  }
}
# tflint-ignore: terraform_unused_declarations
variable "aws_accounts" {
  type = map(string)
  default = {

    idseq-dev = "491013321714"

    idseq-prod = "283694049553"

    idseq-staging = "030998640247"

    idseq-support = "941377154785"

  }
}
