# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "aws-params-secrets-setup" {
  source     = "github.com/chanzuckerberg/cztack//aws-params-secrets-setup?ref=v0.104.2"
  alias_name = local.alias_name
  env        = local.env
  owner      = local.owner
  project    = local.project
  service    = local.service



}
