name: Plan all Components
run-name: Plan all Components in env ${{ inputs.environment || github.base_ref || github.ref_name }} branch ${{ github.base_ref || github.ref_name }} by ${{ github.actor }}

on:
  push:
    branches:
      - development
      - staging
      - main
      - 'releases/**'
  pull_request:
    branches:
      - development
      - staging
      - main
      - 'releases/**'
  workflow_dispatch:
    inputs:
      environment:
        description: Both Github Environment and AWS Environment
        required: true
        type: environment
        default: dev

env:
  branch_name: ${{ github.base_ref || github.ref_name }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}-${{ inputs.environment }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  should-plan:
    name: Check if Terraform Plan should be performed
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.calculate-environment.outputs.environment }}
      components: ${{ steps.list-components.outputs.components }}
    steps:
      - name: Calculate Environment
        id: calculate-environment
        # TODO: Handle Releases
        run: |
          echo "branch_name=${{ env.branch_name }}"
          echo "environment=${{ inputs.environment }}"
          echo "| Planning | Environment | Branch |" >> "$GITHUB_STEP_SUMMARY"
          echo "| ---------------- | ----------- | ------ |" >> "$GITHUB_STEP_SUMMARY"
          if [[ -n "${{ inputs.environment }}" ]]; then
            echo "environment=${{ inputs.environment }}" >> "$GITHUB_OUTPUT"
            echo "| :green_circle: Enabled | ${{ inputs.environment }} | ${{ env.branch_name }} |" >> "$GITHUB_STEP_SUMMARY"
          elif [[ "${{ env.branch_name }}" == "development" ]]; then
            echo "environment=dev" >> "$GITHUB_OUTPUT"
            echo "| :green_circle: Enabled | dev | ${{ env.branch_name }} |" >> "$GITHUB_STEP_SUMMARY"
          elif [[ "${{ env.branch_name }}" == "staging" ]]; then
            echo "environment=staging" >> "$GITHUB_OUTPUT"
            echo "| :green_circle: Enabled | staging | ${{ env.branch_name }} |" >> "$GITHUB_STEP_SUMMARY"
          elif [[ "${{ env.branch_name }}" == "main" ]]; then
            echo "environment=prod" >> "$GITHUB_OUTPUT"
            echo "| :green_circle: Enabled | prod | ${{ env.branch_name }} |" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "environment=" >> "$GITHUB_OUTPUT"
            echo "| :yellow_circle: Disabled | | ${{ env.branch_name }} |" >> "$GITHUB_STEP_SUMMARY"
          fi
      - name: Git clone the repository
        if: ${{ steps.calculate-environment.outputs.environment }}
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: List Components
        id: list-components
        if: ${{ steps.calculate-environment.outputs.environment }}
        working-directory: "./terraform/envs/${{ steps.calculate-environment.outputs.environment }}/"
        run: |
          components=$(find . -maxdepth 1 -mindepth 1 -type d -printf '%P\n' | jq -R . | jq -cs 'sort')
          echo "components=$components"
          echo "components=$components" >> "$GITHUB_OUTPUT"

  plan-components:
    name: Terraform Plan each Component
    if: ${{ needs.should-plan.outputs.environment }}
    needs:
      - should-plan
    strategy:
      fail-fast: false
      #max-parallel: 2
      matrix:
        component: ${{ fromJson(needs.should-plan.outputs.components) }}
        exclude:
          - component: fivetran-ssh-nextgen
          - component: route53 # TODO: Enable this!
          - component: s3-tf-state
    uses: ./.github/workflows/plan_component_call.yml
    with:
      environment: ${{ needs.should-plan.outputs.environment }}
      component: ${{ matrix.component }}
    secrets: inherit

  plan-components-summary:
    name: Terraform Plan Results
    if: ${{ !cancelled() }} # && contains(needs.plan-components.result, 'success') }}
    runs-on: ubuntu-latest
    needs:
      - plan-components
    steps:
      - name: Download Results
        uses: actions/download-artifact@v4
        with:
          pattern: result-*
          path: results
      - name: Generate Summary
        run: |
          echo "needs.plan-components.result=${{ needs.plan-components.result }}"
          jq --slurp . results/result-*/*

          echo "|   | Total Changes |" >> "$GITHUB_STEP_SUMMARY"
          echo "| - | ------------- |" >> "$GITHUB_STEP_SUMMARY"
          jq -n '{change_count: [inputs.change_count] | add}' results/result-*/*.json | jq -r '"|\(if .change_count == 0 then ":green_circle:" else ":yellow_circle:" end)|\(.change_count)|"'
          jq -n '{change_count: [inputs.change_count] | add}' results/result-*/*.json | jq -r '"|\(if .change_count == 0 then ":green_circle:" else ":yellow_circle:" end)|\(.change_count)|"' >> "$GITHUB_STEP_SUMMARY"

          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "<br/>" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"

          echo "|   | Component | Changes |" >> "$GITHUB_STEP_SUMMARY"
          echo "| - | --------- | ------- |" >> "$GITHUB_STEP_SUMMARY"
          jq -r '"|\(if .change_count == 0 then ":green_circle:" else ":yellow_circle:" end)|\(.component)|\(.change_count)|"' results/result-*/*.json
          jq -r '"|\(if .change_count == 0 then ":green_circle:" else ":yellow_circle:" end)|\(.component)|\(.change_count)|"' results/result-*/*.json >> "$GITHUB_STEP_SUMMARY"

          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "<br/>" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"

          echo "| Component | Action | Address |" >> "$GITHUB_STEP_SUMMARY"
          echo "| --------- | ------ | ------- |" >> "$GITHUB_STEP_SUMMARY"
          jq -r '.component as $component | .resource_changes[] | "|\($component)|\(.action)|\(.address)|"' results/result-*/*.json
          jq -r '.component as $component | .resource_changes[] | "|\($component)|\(.action)|\(.address)|"' results/result-*/*.json >> "$GITHUB_STEP_SUMMARY"
