name: Plan Component Call

on:
  workflow_call:
    inputs:
      environment:
        description: Both Github Environment and AWS Environment
        type: string
        required: true
      component:
        description: 'Fogg Component, located in the terraform/emvs/<environment>/<component> directory'
        type: string
        required: true
    secrets:
      AUTH0_CLIENT_ID:
        required: true
      AUTH0_CLIENT_SECRET:
        required: true
      AUTH0_DOMAIN:
        required: true
    outputs:
      plan-artifact-id:
        description: The Artifact ID of the generated Terraform Plan
        value: ${{ jobs.plan-component.outputs.plan-artifact-id }}
      result-artifact-id:
        description: The Artifact ID of the Result JSON
        value: ${{ jobs.plan-component.outputs.result-artifact-id }}

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  plan-component:
    name: Plan Component - ${{ inputs.component }}
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-2
    outputs:
      plan-artifact-id: ${{ steps.upload-plan.outputs.artifact-id }}
      result-artifact-id: ${{ steps.upload-result.outputs.artifact-id }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Reconfigure Git to use HTTP authentication
        run: |
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: false
          arch: amd64
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        if: ${{ !env.ACT }}
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/czid-${{ inputs.environment }}-gh-actions-executor
          #role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
          aws-profile: idseq-${{ inputs.environment }}
      - name: Configure AWS Credentials for local execution using nektos act
        uses: aws-actions/configure-aws-credentials@v6.1.0
        if: ${{ env.ACT }}
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          output-env-credentials: true
          #role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
          aws-profile: idseq-${{ inputs.environment }}
      - name: Setup Terraform
        run: |
          make terraform
          .fogg/tfenv/bin/terraform --version
      - name: Terraform Plan
        id: terraform-plan
        if: ${{ hashFiles('./terraform/envs/${{ inputs.environment }}/${{ inputs.component }}/**') != '' }}
        working-directory: ./terraform/envs/${{ inputs.environment }}/${{ inputs.component }}/
        env:
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
        # TODO: Handle special cases, like route53 which needs idseq-prod access; or fix route53 to be profile-specific only
        # NOTE: make check-plan should be sufficient, but it doesn't leave the plan file after it executes
        run: |
          make check-auth
          ${{ github.workspace }}/.fogg/tfenv/bin/terraform init -input=false -upgrade
          echo "Plan will be created in: ${{ github.workspace }}/tf.plan"
          set +e
          ${{ github.workspace }}/.fogg/tfenv/bin/terraform plan -input=false -detailed-exitcode -refresh=false -out="${{ github.workspace }}/tf.plan"
          exitcode=$?
          echo "Terraform exited with exit-code $exitcode"
          if [[ $exitcode -eq 1 ]]; then
            exit $exitcode
          fi
          set -e
          ${{ github.workspace }}/.fogg/tfenv/bin/terraform show -json "${{ github.workspace }}/tf.plan" > plan.json
          jq '.resource_changes[] | select(.change.actions[0] != "no-op" and .change.actions[0] != "read")' plan.json | jq '{address, action: .change.actions[0]}' | jq -c --slurp . > "${{ github.workspace }}/resource_changes.json"
          jq -c . "${{ github.workspace }}/resource_changes.json"
      - name: Terraform Plan
        id: terraform-plan
        if: ${{ hashFiles('./terraform/envs/${{ inputs.environment }}/${{ inputs.component }}/**') == '' }}
        # NOTE: make check-plan should be sufficient, but it doesn't leave the plan file after it executes
        run: |
          jq -cn '[]' > "${{ github.workspace }}/resource_changes.json"
      # TODO: Only uncomment for local execution via nektos act, when testing outputs and artifacts
      #- name: Terraform Plan
      #  id: terraform-plan
      #  run: |
      #    echo foo > "${{ github.workspace }}/tf.plan"
      #    jq -cn '$ARGS.positional' --jsonargs '{"address": "foo", "action": "create"}' '{"address": "bar", "action": "update"}' '{"address": "baz", "action": "delete"}' > "${{ github.workspace }}/resource_changes.json"
      - name: Upload Plan as Artifact
        id: upload-plan
        if: ${{ hashFiles('./terraform/envs/${{ inputs.environment }}/${{ inputs.component }}/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: plan-${{ inputs.component }}
          path: ${{ github.workspace }}/tf.plan
          retention-days: 1
          compression-level: 0 # Plan files are already pretty compact, and max compression gives at best 10% savings
          if-no-files-found: error
      - name: Create Result JSON
        id: create-result
        run: |
          change_count=$(jq 'length' "${{ github.workspace }}/resource_changes.json")
          echo "change-count=$change_count"
          jq -cnS \
            --arg component "${{ inputs.component }}" \
            --arg artifact_name "plan-${{ inputs.component }}" \
            --arg artifact_id "${{ steps.upload-plan.outputs.artifact-id }}" \
            --argjson change_count "$change_count" \
            --argjson resource_changes $(<"${{ github.workspace }}/resource_changes.json") \
            '$ARGS.named' > "${{ github.workspace }}/result.json"
          jq . "${{ github.workspace }}/result.json"
      - name: Upload Result JSON as Artifact
        id: upload-result
        uses: actions/upload-artifact@v5
        with:
          name: result-${{ inputs.component }}
          path: ${{ github.workspace }}/result.json
          retention-days: 1
          if-no-files-found: error
